name             'indochino-apache2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures indochino-apache2'
long_description 'Installs/Configures indochino-apache2'
version          '0.1.3'

depends 'apache2'
depends 'indochino-php'
